version: '2.0'
services:
  redis:
    image: redis:alpine

  db:
    image: mariadb:10.1
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_file_format=Barracuda, --innodb_large_prefix=1, --innodb_file_per_table=1]
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:2002:8080

  php:
    image: dpfaffenbauer/pimcore:PHP7.2-apache
    volumes:
      - .:/var/www/html:cached
    ports:
     - "127.0.0.1:2000:80"
     - "127.0.0.1:2001:443"
    links:
     - db:db
     - redis:redis

  php-debug:
    image: dpfaffenbauer/pimcore:PHP7.2-apache-debug
    volumes:
      - .:/var/www/html:cached
    ports:
     - "127.0.0.1:2006:80"
    links:
     - db:db
     - redis:redis
    environment:
      - PHP_IDE_CONFIG="serverName=localhost"

volumes:
  pimcore-database:
